[package]
name = "pandoc-rustful-api"
version = "0.1.0"
authors = ["Christian Fries <christian.fries123@gmail.com>"]
edition = "2018"

[dependencies]
rocket = "0.4.10"
#rocket = {git = "https://github.com/SergioBenitez/Rocket", branch = "master"}
rocket_okapi = "0.6.0-alpha-1"
schemars = {version = "0.8.3", features = ["preserve_order"]}
okapi = { version = "0.5.0-alpha-1", features = ["derive_json_schema"] }
serde = "1.0.126"
serde_json = "1.0.64"
chrono = { version="0.4.19", features = ["serde"] }
zip = "0.5"